const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert');
const root=require('node:path').resolve(__dirname,'..');
const html=fs.readFileSync(root+'/static/admin.html','utf8');
const scripts=[...html.matchAll(/<script src="\/static\/([^"?]+)(?:\?[^" ]*)?"><\/script>/g)].map(m=>m[1]);
const assets=Array.from({length:30},(_,i)=>({id:'asset'+i,type:['image','video','pdf','website'][i%4],name:'Asset '+i,media_url:'/media/'+i,url:'https://example.com',display_mode:'fit',size_bytes:100,pdf_page_seconds:10,video_muted:true}));
const playlists=[{id:'playlist',name:'Test',is_active:true,items:assets.map((a,i)=>({id:'item'+i,asset_id:a.id,asset_name:a.name,position:i,duration_seconds:15,enabled:true}))}];
const status={player_name:'Test',playback:{state:'playing'},disk:{total:100,used:50,free:50},ip_addresses:['192.168.1.2'],version:'rc8'};
const dom=new JSDOM(html.replace(/<script.*?<\/script>/g,''),{runScripts:'dangerously',pretendToBeVisual:true,url:'http://192.168.1.2:8000/'});
const w=dom.window;
w.fetch=async p=>({ok:true,status:200,text:async()=>JSON.stringify(p==='/api/assets'?assets:p==='/api/playlists'?playlists:p==='/api/status'?status:p==='/api/settings'?{player_name:'Test',max_upload_mb:500,admin_username:'pi'}:p==='/api/logs'?[]:{})});
let mutations=0;const obs=new w.MutationObserver(rs=>mutations+=rs.length);obs.observe(w.document.body,{childList:true,subtree:true});
for(const file of scripts){const s=w.document.createElement('script');s.textContent=fs.readFileSync(root+'/static/'+file,'utf8');w.document.body.appendChild(s);}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{await wait(600);const first=mutations;await wait(300);assert.equal(mutations,first,'Full admin did not settle');w.document.querySelector('[data-tab="assets"]').click();assert.equal(w.document.querySelector('#tab-assets').classList.contains('hidden'),false);w.document.querySelector('#refresh-assets').click();await wait(400);const second=mutations;await wait(300);assert.equal(mutations,second,'Refresh did not settle');assert.equal(w.document.querySelectorAll('script').length,3);
  assert.ok(!scripts.some(file=>/video-ui|playlist-timer|image-mode/.test(file)));
  const video=assets.find(a=>a.type==='video');
  w.document.querySelector(`[data-edit-asset="${video.id}"]`).click();await wait(100);
  assert.ok(w.document.querySelector('[data-video-muted]'));
  assert.ok(w.document.querySelector('[data-video-loop]'));
  w.document.querySelector(`[data-cancel-asset-edit="${video.id}"]`).click();await wait(100);
  const pdf=assets.find(a=>a.type==='pdf');
  w.document.querySelector(`[data-edit-asset="${pdf.id}"]`).click();await wait(100);
  assert.ok(w.document.querySelector('[data-asset-edit-pdf-once]'));
  const select=w.document.querySelector('[data-add-item] select');
  select.value=video.id;select.dispatchEvent(new w.Event('change',{bubbles:true}));
  assert.equal(select.closest('form').querySelector('[name="duration_seconds"]').disabled,true);
  select.value=pdf.id;select.dispatchEvent(new w.Event('change',{bubbles:true}));
  assert.equal(select.closest('form').querySelector('[name="duration_seconds"]').disabled,false);
  await wait(250);const final=mutations;await wait(150);assert.equal(mutations,final);
  console.log('PASS: direct admin rendering, mixed assets, refresh, edit controls and automatic timing');})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{obs.disconnect();w.close()});
